" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
filetype off
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'tomasr/molokai'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'klen/python-mode'
Plugin 'The-NERD-Commenter'

Plugin 'Yggdroot/indentLine' " A vim plugin to display the indention levels with thin vertical lines
Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
"Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'airblade/vim-gitgutter' " A Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks.

Plugin 'tomtom/tlib_vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

Plugin 'fatih/vim-go'

call vundle#end()

" Pymode
let g:pymode_python = 'python'
let g:pymode_rope = 0
let g:pymode_rope_goto_definition_cmd = 'vnew'
let g:pymode_folding = 0
let g:pymode_lint_unmodified = 1
let g:pymode_lint_checkers = ['pylint', 'pyflakes', 'pep8', 'mccabe']
" C0111 - Missing docstrings
" W0703 - Cathing too general exception
let g:pymode_lint_ignore = [ "C0111", "W0703", ]

" vim-go
let g:go_auto_type_info = 0
let g:go_addtags_transform = "snakecase"
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_play_open_browser = 1
let g:go_dispatch_enabled = 1
let g:go_def_reuse_buffer = 0
let g:go_metalinter_autosave = 1

" Plugins settings
" Powerline setup for MacVim/ GVim
set laststatus=2
if has("gui_running")
    set lines=999 columns=999
    let s:uname = system("uname")
    if s:uname == "Linux\n"
        set guifont=Ubuntu\ Mono\ for\ Powerline\ 12
    elseif s:uname == "Darwin\n"
        set guifont=Inconsolata\ for\ Powerline:h15
    endif
elseif $TERM == 'xterm-256color'
    set t_Co=256
    colorscheme desert256
endif

" YAML
 autocmd Filetype yaml setlocal ts=2 sw=2 expandtab

" Supertab
let g:SuperTabDefaultCompletionType = "<c-n>"

" Airline
let airline_enable_branch = 0
let g:airline_section_b= ""
let g:go_version_warning = 0

" Pymode
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_lint_unmodified = 1
let g:pymode_lint_checkers = ['pep8', 'pyflakes']
autocmd BufWriteCmd *.py write || :PymodeLint

" CtrlP Settings
let g:ctrlp_max_height = 30
set wildignore+=*.pyc,*_build/*,*/coverage/*,*/devenv/*

"Removes scrollbars
set guioptions-=r
set guioptions-=T

"Disable scrollbar in NERDTree
set guioptions-=L

" Jedi-vim
let g:jedi#use_splits_not_buffers = "left"

" Add one space after NERDCommented comment
let NERDSpaceDelims=1

" Personal settings

set shell=/bin/sh
let g:go_fmt_command = "goimports"

filetype on
filetype plugin on
filetype plugin indent on
set modeline
syntax enable
autocmd! bufwritepost ~/.vimrc source % " Autoupdate changes
colors molokai " Color scheme
set splitbelow " New files open on the right
set splitright " New files open on the bottom
" Disable backups
set nobackup
set noswapfile
set nowritebackup
set cursorline

" Use 4 spaces instead of tabs
set tabstop=4 " Number of space chars inserted
set shiftwidth=4 " Number of space chars inserted for identation
set expandtab " Spaces instead of tabs

" Use 2 spaces instead of tabs for HTML files
autocmd FileType html setlocal shiftwidth=2 tabstop=2

set nojoinspaces " Dont leave spaces between joined lines
set nu " Line numbers
set hlsearch " Highlight all search matches
set incsearch " Move cursor to the matched string, while typing
set ignorecase

set backspace=indent,eol,start " backspace doesn't work in insert mode

" Temporary turn off hlsearch
nnoremap <silent> <leader>l :noh<CR>

" Fix identation when pasting in Insert mode
set pastetoggle=<F3>

" Remap Ctrl+v to paste text in insert mode
inoremap <C-v> <F3><C-r>+<F3>

" Toggle NERDTree hotkey
map <F2> :NERDTreeToggle<CR>

" Exit insert mode with jk/jj
inoremap jk <Esc>
inoremap jj <Esc>
nmap <F1> :w<CR>
vmap <C-S> <Esc><C-S>gv
imap <C-S> <Esc><C-S>gi

"Easier navigation through split windows
nnoremap <C-J> <C-W><Down>
nnoremap <C-K> <C-W><Up>
nnoremap <C-L> <C-W><Right>
nnoremap <C-H> <C-W><Left>

" Old habits never die
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

nnoremap <C-c> :bn\|bd #<CR>

" Remap up and down arrows to go to previous/next change in airblade/gitgutter
nmap <Up> <Plug>GitGutterPrevHunk
nmap <Down> <Plug>GitGutterNextHunk
nmap <Right> <Plug>GitGutterPreviewHunk
nmap <Left> <Plug>GitGutterUndoHunk
