" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
filetype off
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tomasr/molokai'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'klen/python-mode'
Plugin 'The-NERD-Commenter'

Plugin 'Yggdroot/indentLine'
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'tpope/vim-surround'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'nanotech/jellybeans.vim'
Plugin 'airblade/vim-gitgutter'

Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

Plugin 'fatih/vim-go'

call vundle#end()

" Plugins settings
" Powerline setup for MacVim/ GVim
set laststatus=2
if has("gui_running")
    set lines=999 columns=999
    let s:uname = system("uname")
    if s:uname == "Linux\n"
        set guifont=Ubuntu\ Mono\ for\ Powerline\ 12
    elseif s:uname == "Darwin\n"
        set guifont=Inconsolata\ for\ Powerline:h15
    endif
else
    set term=xterm-256color
endif

" YAML
 autocmd Filetype yaml setlocal ts=2 sw=2 expandtab

" Supertab
let g:SuperTabDefaultCompletionType = "<c-n>"

" Airline
let airline_enable_branch = 0
let g:airline_section_b= ""

" Pymode
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_lint_unmodified = 1
let g:pymode_lint_checkers = ['pep8', 'pyflakes']
au BufWriteCmd *.py write || :PymodeLint

" CtrlP Settings
let g:ctrlp_max_height = 30
set wildignore+=*.pyc,*_build/*,*/coverage/*,*/devenv/*

"Removes scrollbars
set guioptions-=r
set guioptions-=T

"Disable scrollbar in NERDTree
set guioptions-=L

" Jedi-vim
let g:jedi#use_splits_not_buffers = "left"

" Add one space after NERDCommented comment
let NERDSpaceDelims=1

" Personal settings

set shell=/bin/sh
let g:go_fmt_command = "goimports"

filetype on
filetype plugin on
filetype plugin indent on
set modeline
syntax enable
autocmd! bufwritepost ~/.vimrc source % " Autoupdate changes
colors molokai " Color scheme
set splitbelow " New files open on the right
set splitright " New files open on the bottom
" Disable backups
set nobackup
set noswapfile
set nowritebackup
set cursorline

" Use 4 spaces instead of tabs
set tabstop=4 " Number of space chars inserted
set shiftwidth=4 " Number of space chars inserted for identation
set expandtab " Spaces instead of tabs
" Use 2 spaces instead of tabs for HTML files
autocmd FileType html setlocal shiftwidth=2 tabstop=2

set nojoinspaces " Dont leave spaces between joined lines
set nu " Line numbers
set hlsearch " Highlight all search matches
set incsearch " Move cursor to the matched string, while typing
set ignorecase
" Temporary turn off hlsearch
nnoremap <silent> <leader>l :noh<CR>
" Fix identation when pasting in Insert mode
set pastetoggle=<F3>
" Remap Ctrl+v to paste text in insert mode
inoremap <C-v> <F3><C-r>+<F3>
" Toggle NERDTree hotkey
map <F2> :NERDTreeToggle<CR>
" Exit insert mode with jk/jj
inoremap jk <Esc>
inoremap jj <Esc>
nmap <F1> :w<CR>
vmap <C-S> <Esc><C-S>gv
imap <C-S> <Esc><C-S>gi
"Easier navigation through split windows
nnoremap <C-J> <C-W><Down>
nnoremap <C-K> <C-W><Up>
nnoremap <C-L> <C-W><Right>
nnoremap <C-H> <C-W><Left>

"execute go run
nmap <F9>  :GoRun <CR>

" Old habits never die
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

nnoremap <C-c> :bn\|bd #<CR>

" Remap up and down arrows to go to previous/next change in airblade/gitgutter
nmap <Up> <Plug>GitGutterPrevHunk
nmap <Down> <Plug>GitGutterNextHunk
nmap <Right> <Plug>GitGutterPreviewHunk
nmap <Left> <Plug>GitGutterUndoHunk
