alias gpl="git pull"
alias gb="git branch"
alias gpsh="git push"
alias gc="git commit"
alias gs="git status"
alias ga="git add -u"
alias gf="git fetch"
alias ccat='pygmentize -g'
alias lab='cd /repos/env/deploy'
alias tmuxex='export TERM=screen-256color-bce'
alias ka="sudo kill -9"
alias drm="docker rm -f"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias gd="git diff"
alias w="cd /home/filcho/work/src"
alias rmpyc="find . -name "*.pyc" -exec rm -f {} \;"
